# Generated by Django 3.1.3 on 2020-11-09 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'ordering': (),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
            options={
                'ordering': (),
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(choices=[('h', 'Hospedagem'), ('a', 'Apartamento'), ('o', 'Hostel')], max_length=10)),
                ('price', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrine.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrine.country')),
            ],
            options={
                'ordering': (),
            },
        ),
        migrations.CreateModel(
            name='Vitrine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('itens', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrine.hotel')),
            ],
            options={
                'ordering': (),
            },
        ),
    ]
