# Generated by Django 3.1.3 on 2020-11-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitrine',
            name='itens',
        ),
        migrations.AddField(
            model_name='vitrine',
            name='itens',
            field=models.ManyToManyField(to='vitrine.Hotel'),
        ),
    ]
