# Generated by Django 3.1.3 on 2020-11-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_auto_20201109_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('hospedagem', 'Hospedagem'), ('apartamento', 'Apartamento'), ('hostel', 'Hostel')], max_length=20),
        ),
    ]
