# Generated by Django 3.1.3 on 2020-11-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_auto_20201110_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
